#!/bin/bash

if [[ $1 == "" ]] || [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
	echo "smith <host>"
	echo "smith http.//example.com"
	echo "or"
	echo "smith <list of hosts>"
	echo "smith list.txt"
	exit 1
fi

meg -d 100 -c 200 wordlist.txt "$1"

search() {
	results=$(grep -rli "$1" out)
	if [[ -n "$results" ]]; then
		while read -r url; do
			head -1 "$url";
		done <<< "$results"
	fi
}

echo "==> Webalizer Instances <=="
search "webalizer"
echo

echo "==> GitLab Instances <=="
search "Explore GitLab"
echo

echo "==> Gitea Instances <=="
search "Gitea Version:"
echo

echo "==> phpinfo() pages <=="
search "PHP Version"
echo

echo "==> Public ssh keys <=="
search "ssh-rsa"
echo

echo "==> Apache Server Status files <=="
search "Apache Server Status for"
echo

echo "==> Perl CGI environment variables <=="
search "GATEWAY_INTERFACE=\"CGI"
echo