#!/bin/bash

GREEN='\033[0;32m'
END='\033[0m'

if [[ $1 == "" ]] || [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
	echo "smith <host>"
	echo "smith http://example.com"
	echo "or"
	echo "smith <list of hosts>"
	echo "smith list.txt"
	exit 1
fi

meg -d 100 -c 200 wordlist.txt "$1" 2> /dev/null

search() {
	results=$(grep -rliE "$1" out)
	if [[ -n "$results" ]]; then
		while read -r url; do
			head -1 "$url";
			echo;
		done <<< "$results"
	fi
}

spit() {
	echo -e "${GREEN}==> $1 <==${END}"
}

spit "Webalizer Instances"
search "webalizer"

spit "GitLab Instances"
search "Explore GitLab"

spit "Phppgadmin instance"
search "phppgadmin:"

spit "/etc/passwd"
search "root:x:0:0:root:/root:/bin/bash"

spit "Gitea Instances"
search "Gitea Version:"

spit "phpinfo() pages"
search "PHP Version"

spit "Public ssh keys"
search "ssh-rsa"

spit "Apache Server Status files"
search "Apache Server Status for"

spit "Perl CGI environment variables"
search "GATEWAY_INTERFACE=\"CGI"

spit "CRLF injection vulnerabilities"
search "< Set-Cookie: ?crlf"

spit "Open redirect vulnerabilities"
search '< location: (https?:)?[/\\]{2,}example.com'
